# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache st typings
      uses: actions/cache@v3
      with:
        key: st
        path: |
          ~/.cache/scalablytyped
          ~/.ivy2/local/org.scalablytyped
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version-file: .github/workflows/.java-version
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        # node-version: # optional
        cache: yarn
    - name: Run tests
      run: sbt test
    - name: Build Webpack
      run: sbt "fastOptJS / webpack"
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
      with:
        configs-ignore: scala-tool scala-doc-tool
